//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.investing.com/currencies/eur-usd-commentary")]
        public string HomePage {
            get {
                return ((string)(this["HomePage"]));
            }
            set {
                this["HomePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsLogVisible {
            get {
                return ((bool)(this["IsLogVisible"]));
            }
            set {
                this["IsLogVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>theBigX</string>
  <string>Quotes</string>
  <string>broker_promotions</string>
  <string>webinars_new</string>
  <string>findABroker</string>
  <string>theDisclaimer</string>
  <string>footerWrapper</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FilterIds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FilterIds"]));
            }
            set {
                this["FilterIds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFilterContent {
            get {
                return ((bool)(this["IsFilterContent"]));
            }
            set {
                this["IsFilterContent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFilterMessages {
            get {
                return ((bool)(this["IsFilterMessages"]));
            }
            set {
                this["IsFilterMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>div-gpt-ad</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FilterIdsStartsWith {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FilterIdsStartsWith"]));
            }
            set {
                this["FilterIdsStartsWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>midHeader</string>
  <string>tradeNowRightColumn</string>
  <string>js-edukit-wrapper</string>
  <string>doubleLineSeperator</string>
  <string>curExp</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FilterClasses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FilterClasses"]));
            }
            set {
                this["FilterClasses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>/members/201938949</string>
  <string>/members/200910201</string>
  <string>/members/201725043</string>
  <string>/members/200529694</string>
  <string>/members/201163763</string>
  <string>/members/201251630</string>
  <string>/members/200620745</string>
  <string>/members/200118885</string>
  <string>/members/200024378</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FilterMessages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FilterMessages"]));
            }
            set {
                this["FilterMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFilterMessagesInverseMode {
            get {
                return ((bool)(this["IsFilterMessagesInverseMode"]));
            }
            set {
                this["IsFilterMessagesInverseMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAddressVisible {
            get {
                return ((bool)(this["IsAddressVisible"]));
            }
            set {
                this["IsAddressVisible"] = value;
            }
        }
    }
}
